
import { defineConfig } from 'vite';
import { viteStaticCopy } from 'vite-plugin-static-copy';

export default defineConfig({
  base: '/whisper-share/',
  worker: {
    format: 'es',
    rollupOptions: {
      output: {
        // Configure the output name for worker scripts (don't use service-worker.js)
        entryFileNames: 'ffmpeg-worker.js',
        // Default naming for any chunks or assets generated by the worker build itself
        chunkFileNames: 'worker-chunks/[name]-[hash].js',
        assetFileNames: 'worker-assets/[name]-[hash].[ext]',
      }
    }
  },
  optimizeDeps: {
    exclude: ['@ffmpeg/ffmpeg', '@ffmpeg/util', '@ffmpeg/core']
  },
  server: {
    headers: {
      'Cross-Origin-Embedder-Policy': 'require-corp',
      'Cross-Origin-Opener-Policy': 'same-origin',
    },
    fs: {
      allow: ['..', './node_modules']
    }
  },
  assetsInclude: ['**/*.wasm'],
  build: {
    rollupOptions: {
      output: {
        // Standard Vite naming for the main application's assets
        entryFileNames: '[name]-[hash].js',
        chunkFileNames: '[name]-[hash].js',
        assetFileNames: '[name]-[hash].[ext]',
      },
    },
  },
  plugins: [
    viteStaticCopy({
      targets: [
        {
          src: 'node_modules/@ffmpeg/core/dist/esm/ffmpeg-core.{js,wasm}',
          dest: ''
        },
        {
          src: 'service-worker.js',
          dest: ''
        }
      ]
    })
  ],
});
